### ISSUE TITLE
Proceedings startpage and individual pages are broken

### ISSUE THREAD

**Issue by manuelhaussmann** [mlresearch/v108#22]
On the AISTATS proceedings start page (http://proceedings.mlr.press/v108/) the **[abs]** does not link to to the actual page of the respective paper, but rather to an edit of the config.yaml (https://github.com/mlresearch/v108/edit/gh-pages/_config.yml).

Additionally the **[Download PDF]** are missing, while the **[Supplementary PDF]** works as desired. 
Accessing the abstract page by hand it is created as usual, just in the related material again the main paper pdfs are missing (see e.g. http://proceedings.mlr.press/v108/pedregosa20a.html). 

The behaviour is consistent over all papers, while the other proceedings seem unaffected (although I only checked a handful).

**Comment by lawrennd** [comment]
Thanks Manuel for highlighting this! 

I'd introduced a bug in the jekyll theme, which I believe I've fixed now. So I think this is all working. Apologies for messing this up.

I'll close now, but feel free to reopen if there's still a problem.

**Comment by manuelhaussmann** [comment]
Yes, everything seems to be fixed again. Thanks!
